# Miscellaneous

## Something related to in-class exercises and grading rubic

* Please do remember to submit your codes!
* Download the codes from ``Canvas`` and then start to do the exercises following the instruction in the codes.
* You do not need to write too-detailed notes, the focus is still coding.
* Do not write the codes related to the lecture in the exercise, which could help my grading easier.
* Make sure your codes satisfying the requirements of the exercise. 

In-class exercise grading rubic (Tentative)

| Item                                                                                     | Grades |
|------------------------------------------------------------------------------------------|:------:|
| Codes could generate the results required by the problems                                | 6      |
| Necessary notes to indicate the general idea (usage, function, purpose, or machanism)    | 3      |
| Codes and notes are neat and well-organized                                              | 1      |

## Comparison between R and Stata

As some students asked in class, 

*Why the school still teaches students Stata when no one uses them?*

I covered several points in class simply which I think is not enough. I think this question is more related to the comparison between ``R`` and ``Stata``. I read several articles [@john2014;@michael2014] online and list some key points in the table below. I hope this will give a better understanding of both ``R`` and ``Stata``.

**Advantages of R** (More Flexible but less Formal)

* Free and Open source
* More advanced technique packages
* Deal with more than one datasets (big data) at the same time
* Deal with not only data analysis tasks

**Advantages of Stata** (More Formal but less Flexible)

* More algorithms, packages, and implementations of econometircs
* Faster
* It is supported by Statacorp so the result is reliable
* It presents results in a clear format
* Syntax is simple and standard for most data analysis
* Help document is formal

Besides those advantages, they have a lot of overlaps with each other. People cannot say one is absolutely better than the other. People choose them based on their task requirements. Sometimes, people install both of them in their computers (e.g. my laptop has both of them).
