# Final Project

## Description
R is the tool serving for data analysis and results descprition. In the final project, you will use the R programming skills you learn from this course and also the knowledge outside the course (other R techniques you are interested in or your professional knowledge in your study major) to solve a research question. The research question could be related your study field (e.g. public policy, urban and regional planning), or what you are interested, or your previous course or research project but you do it with R. You could use any packages in R to solve the problem. For example, you could use plots to do descriptive analysis. Or you could use regression to find more complicated correlation or causality results.

## Timeline

To accomplish the final project, you need to finish three tasks.

|   | Task          | Descriptions                                             | Due Date |
|:-:|---------------|----------------------------------------------------------|----------|
| 1 | Proposal      | Your research question and background introduction       | 5th Nov. |
| 2 | Data analysis | The results for data manipulation and data visualization | 3th Dec. |
| 3 | Final report  | A short report of your project                           | 22nd Dec.|


## Proposal

In this part, you will need to submit the proposal file (either word or pdf). The instructor will give you feedback but will not grade this part. The rubric is just for helping you check the requirements.

| Item                                                                                                                      |
|---------------------------------------------------------------------------------------------------------------------------|
| Research question and description of research question is clear                                                        |
| Background introduction is related to the research topic and could support that the research question is valid and meaningful|
| Clearly state the data sources (what is the dataset, where do you find it, what variables you will use from this dataset) |
| State the potential method you will use for data analysis (descriptive analysis, simple regression, etc.) |

The proposal should be less than one page (not including citation), 12 font size, and single space.

## Data analysis

In this part you will submit your dataset, codes, and the file (either word or pdf) including the figures generated by the codes, the tables, and results description in bullet points. Again, the instructor will give you feedback but will not grade this part. The rubric is just for helping you check the requirements.

| Item                                                                                              |
|---------------------------------------------------------------------------------------------------|
| Codes could generate the results                                                                  |
| Necessary notes for the codes                                                                     |
| Codes is neat and well-organized                                                                  |
| Figures contain the necessary parts, well-organized, and visually good/ tables are well-organized |
| Description of the result is clear                                                                |


## Final report

In this part, you will submit your dataset, revised codes, and the final report. The instructor will grade them based on the rubric below. The report should include introduction, data description, method (if necessary), result, and conclusion.

| Category | Item                                                                                                                          | Grades |
|----------|-------------------------------------------------------------------------------------------------------------------------------|--------|
| Codes    | Codes could generate the results (figures, tables, and related numbers)                                                       | 25     |
|          | Necessary notes for the codes                                                                                                 | 10     |
|          | Codes is neat and well-organized                                                                                              | 10     |
| Report   | Research question and description of research question is clear                                                               | 5      |
|          | Background introduction is related to the research topic and could support that the research question is valid and meaningful | 5      |
|          | Clearly state the data sources (what is the dataset, where do you find it, what variables you use from this dataset)          | 5      |
|          | Variable description is provided and well-organized                                                                           | 5      |
|          | Figures contain the necessary parts, well-organized, and visually good/ tables are well-organized                             | 25     |
|          | Description of the result is clear                                                                                            | 5      |
|          | Conclusion is clear, the results are summarized, and implication is meaningful                                                 | 5      |

The final report should be less than three pages (not including citation, tables, and figures), 12 font size, and single space.




